apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-login-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-login-app
  template:
    metadata:
      labels:
        app: nodejs-login-app
    spec:
      containers:
      - name: nodejs-login-app
        image: nodejs-login-app:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-login-app-service
spec:
  selector:
    app: nodejs-login-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
